"""add password hash to users

Revision ID: 80f2e8f26d1e
Revises: b23c5d1b38b0
Create Date: 2026-09-30 16:05:57.252385

"""
import secrets

import bcrypt
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f2e8f26d1e'
down_revision: Union[str, Sequence[str], None] = 'b23c5d1b38b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
        ),
    )

    unusable_password = secrets.token_urlsafe(48)
    unusable_password_hash = bcrypt.hashpw(
        unusable_password.encode("utf-8"),
        bcrypt.gensalt(),
    ).decode("utf-8")

    connection = op.get_bind()

    connection.execute(
        sa.text(
            """
            UPDATE users
            SET password_hash = :password_hash
            """
        ),
        {
            "password_hash": unusable_password_hash,
        },
    )

    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "users",
        "password_hash",
    )
    # ### end Alembic commands ###
