"""add foreign key on user in events

Revision ID: 841ad52df742
Revises: 3aa321ce114d
Create Date: 2026-09-19 17:32:07.870473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841ad52df742'
down_revision: Union[str, Sequence[str], None] = '3aa321ce114d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['created_by_id'], ['id'])
    op.drop_column('events', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("events_created_by_id_fkey", 'events', type_='foreignkey')
    op.drop_column('events', 'created_by_id')
    # ### end Alembic commands ###
