"""split user full name

Revision ID: 4a6e705b383f
Revises: 4ecd4f38d51c
Create Date: 2026-09-20 21:04:04.387878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6e705b383f'
down_revision: Union[str, Sequence[str], None] = '4ecd4f38d51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.String(length=127),
            nullable=True,
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "second_name",
            sa.String(length=127),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE users
        SET
            first_name = CASE
                WHEN POSITION(' ' IN BTRIM(full_name)) > 0
                    THEN SPLIT_PART(BTRIM(full_name), ' ', 1)
                ELSE BTRIM(full_name)
            END,
            second_name = CASE
                WHEN POSITION(' ' IN BTRIM(full_name)) > 0
                    THEN BTRIM(
                        SUBSTRING(
                            BTRIM(full_name)
                            FROM POSITION(' ' IN BTRIM(full_name)) + 1
                        )
                    )
                ELSE ''
            END
        """
    )

    op.alter_column(
        "users",
        "first_name",
        nullable=False,
    )

    op.alter_column(
        "users",
        "second_name",
        nullable=False,
    )

    op.drop_column(
        "users",
        "full_name",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE users
        SET full_name = BTRIM(
            first_name || ' ' || second_name
        )
        """
    )

    op.alter_column(
        "users",
        "full_name",
        nullable=False,
    )

    op.drop_column(
        "users",
        "second_name",
    )

    op.drop_column(
        "users",
        "first_name",
    )
    # ### end Alembic commands ###
